//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAP
    {
        public PHIEUNHAP()
        {
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> ID_NhaCC { get; set; }
        public Nullable<int> ID_DonVi { get; set; }
    
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        public virtual DONVI DONVI { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
